-- * implement scene push/pop
-- * implement remaining transitions
-- * add CCMenu alignment functions
-- * add prioritized updates to CCScheduler and CCNode classes
-- * add non-targeted touch handling
-- * implements batched sprites (using mesh)
-- * implement bitmapped fonts
-- * implement tilemaps (using mesh)
-- * implement bitmapped font labels
-- * lazily create children table
-- * do fast children sort in visit(?)
-- * implement skew
-- * CCEaseElastic(in/out/inout), CCBounce(in/out/inout), CCEaseBack(in/out/inout)
-- * skewBy, skewTo, BezierBy, BezierTo
-- * CCReverseTime, CCAnimate, CCTargetedAction
-- * CCActionCatmullRom
-- * implement particle systems
-- * implement tile map nodes
-- * CCRenderTexture

-- * write alternative version of sprite() that takes (s,t,u,v)
-- * in backend, and try to get TLL to use it
-- * when codea allows (s, t, u, v) to be specfied in sprite()
    -- * add textureRect to CCSprite